name: indoor_regio_cup_app
description: Eine mobile Flutter‑App für den IRC Indoor Regio Cup Check‑In. Diese App ermöglicht das Importieren von Gästelisten per CSV, das Scannen von QR‑Codes, die Anzeige einer Ticketübersicht, den Versand von E‑Mails mit QR‑Codes, das Zurücksetzen von Scan‑Status sowie die Darstellung von Statistiken und einer QR‑Code‑Galerie.

# Version der App. Die Build‑Nummer kann bei Bedarf erhöht werden.
version: 1.0.0+1

# Unterstützte Flutter‑SDK Version
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # HTTP‑Client für API‑Aufrufe
  http: ^0.13.5
  # Datei‑Picker für den CSV‑Import
  file_picker: ^5.2.3
  # Scanner‑Bibliothek für QR‑Codes
  mobile_scanner: ^2.1.0
  # Für Dropdown‑Listen und andere Widgets wird keine zusätzliche Bibliothek benötigt
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true