name: indoor_regio_cup
description: Eine Flutter App für den Indoor Regio Cup
publish_to: "none"

# Versionsnummer: <version>+<build>
version: 1.0.1+2

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.2.2
  mobile_scanner: ^7.1.2
  intl: ^0.18.1
  file_picker: ^5.5.0
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
